window.translateMap = {
    'Ищем оппонента': 'Searching for opponent',
    'Загружаются темы': 'Loading themes',
    'Выбери тему': 'Choose a theme',
    'Играть': 'Play',
    'Нашли ошибку?': 'Find a question?',
    'Загружаемся': 'Loading',
    'Инструкция': 'Instruction',
    'Рейтинг': 'Rating',
    'Язык': 'Language',
    'Настройки': 'Settings',
    'Поздравляем, вы заработали новое достижение': "Congratulations, you've earned a new achievement",
    'Первое достижение': 'New achievement',
    'Победа': 'You win!',
    'Поражение': 'You loose!',
    'Очки за игру': 'Match points',
    'Бонус за игру': 'Finish bonus',
    'Победный бонус': 'Victory bonus',
    'Получено очков': 'Total points',
    'Уровень': 'level',
    'До игры': 'Before game',
    'Заработано': 'Earned',
    '1 вопрос': '1 question',
    '2 вопрос': '2 question',
    '3 вопрос': '3 question',
    '4 вопрос': '4 question',
    '5 вопрос': '5 question',
    '6 вопрос': '6 question',
    '7 вопрос': '7 question',
    'Всего': 'Match points',
    'Играть еще раз': 'Play another',
    'Рейтинг': 'Rating',
    'Поделиться': 'Share'
};