// Generated by CoffeeScript 1.4.0
(function() {
  var $$, AuthCrypto, crypto;

  $$ = require('2dollars');

  crypto = require('crypto');

  module.exports = AuthCrypto = {
    algorithm: 'aes-256-ctr',
    password: 'CHANGE_THIS_PASSWORD_PLEASE-l9MB2tE3hTiI0W',
    encryptString: function(text, password) {
      var cipher, crypted;
      if (password == null) {
        password = null;
      }
      if (password === null) {
        password = this.password;
      }
      cipher = crypto.createCipher(algorithm, password);
      crypted = cipher.update(text, 'utf8', 'base64');
      crypted += cipher.final('base64');
      return $$.base64UrlEncode(crypted);
    },
    decryptString: function(text, password) {
      var dec, decipher;
      if (password == null) {
        password = null;
      }
      if (password === null) {
        password = this.password;
      }
      text = $$.base64UrlDecode(text);
      decipher = crypto.createDecipher(this.algorithm, password);
      dec = decipher.update(text, 'base64', 'utf8');
      dec += decipher.final('utf8');
      return dec;
    },
    encryptObject: function(object) {
      return this.encryptString(JSON.stringify(object));
    },
    decryptObject: function(token) {
      console.log;
      return JSON.parse(this.decryptString(token));
    },
    encrypt: function(object) {
      return this.encryptObject(object);
    },
    decrypt: function(token) {
      return this.decryptObject(token);
    },
    /*
        Sample Express-like controller req,res wrapper
    
        You can copy this and  paste & change in real controller
    */

    findCreateUpdate: $$.findCreateUpdate,
    controller: function(req, res, UserModel, UserModelConvert) {
      var rawData, redirect, token, userData, v;
      if (UserModelConvert == null) {
        UserModelConvert = null;
      }
      if (UserModelConvert === null) {
        UserModelConvert = function(rawData) {
          var userData;
          userData = {
            id: rawData.username,
            name: rawData.name,
            avatar: rawData.avatar,
            role: rawData.role
          };
          return userData;
        };
      }
      token = req.param("token");
      redirect = req.param("redirect");
      if (!redirect) {
        redirect = req.param("returnUrl");
      }
      v = req.param("v");
      if (!v) {
        return res.serverError({
          err: "не указана версия"
        });
      }
      rawData = AuthCrypto.decrypt(token);
      if (!rawData) {
        return res.serverError({
          err: "не удалось расшифровать токен"
        });
      }
      userData = UserModelConvert(rawData);
      if (!rawData.id) {
        return res.serverError({
          err: "не удалось расшифровать ID в токене"
        });
      }
      return this.findCreateUpdate(UserModel, userData, function(err, user) {
        return req.login(user, function(err) {
          if (redirect) {
            return res.redirect(redirect);
          } else {
            return res.json(user);
          }
        });
      });
    },
    gatewayResolve: function(req, res) {
      var params, redirect, token, userData;
      if (!req.user) {
        params = req.allParams();
        redirect = "/auth/gateway?" + Object.keys(params).filter(function(key) {
          return typeof params[key] !== "undefined";
        }).map(function(key) {
          return key + "=" + encodeURIComponent(params[key]);
        }).join("&");
        return res.redirect("/auth/login?redirect=" + encodeURIComponent(redirect));
      }
      userData = {
        id: req.user.id,
        username: req.user.id + "@appberry.ru",
        name: req.user.getFullName(),
        avatar: req.user.getAvatar(),
        role: req.user.role || "user",
        platform: "appberry.ru"
      };
      token = AuthCrypto.encrypt(userData);
      return res.redirect(req.param("redirect") + "&token=" + token);
    },
    gateway: function(req, res, User) {
      var url;
      url = req.protocol + '://' + req.host + "/auth/crypto?v=1&redirect=" + encodeURIComponent(req.url);
      return res.redirect(req._sails.config.authcrypto.gateway + "?token=123&redirect=" + encodeURIComponent(url));
      return res.redirect2({
        _url: req._sails.config.authcrypto.gateway,
        token: 123,
        redirect: {
          _url: req.protocol + '://' + req.host + "/auth/crypto",
          v: 1,
          redirect: req.url
        }
      });
    }
  };

}).call(this);
